name: Deploy a lambda function
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cheak out code
      uses: actions/checkout@v4
    - name: Install python 3.8
      uses: actions/setup-python@v5
      with: 
        python-version: 3.8
    - name: Install linter
      run: pip install flake8
    - name: Lint
      run: | 
          cd function
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cheak out code
      uses: actions/checkout@v4
    - name: Install python 3.8
      uses: actions/setup-python@v5
      with: 
        python-version: 3.8
    - name: Install libraris
      run: |
          cd function
          python -m pip install --upgrade pip 
          pip install -r requirements.txt -t
    - name: Zip function
      run: | 
          cd function
          zip -r ../${{ github.sha }}.zip .
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: ${{ github.sha }}.zip
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Create release
      uses: ncipollo/release-action@v1.14
      with:
        tag: ${{ github.run_number }}
        name: Releas from ${{ github.run_number }}
        body: New release from ${{ github.sha }}
        draft: false
        prerelease: false
        
        
        
